#index:
#    path: /
#    controller: App\Controller\DefaultController::index
showById:
    path: /fallecido/{id}
    controller: App\Controller\FallecidosController::showById
editFallecido:
    path: /editFallecido/{id}
    controller: App\Controller\FallecidosController::editFallecido
showFallecidoByMun:
    path: /{idmunicipio}
    controller: App\Controller\FallecidosController::showFallecidoByMun